/* =========================================================================
   RPM Móviles — STOCK DE VEHÍCULOS (datos de ejemplo / placeholders)
   -------------------------------------------------------------------------
   Estructura preparada para cargar autos dinámicamente en el futuro.
   Para conectar con un CRM/API, reemplazar este array por un fetch():

     async function loadVehicles() {
       const res = await fetch('/api/vehiculos');
       return res.json();
     }

   Cada objeto representa una card del catálogo.
   - imagenes: array de URLs. Si está vacío se usa el placeholder.
   - estado: "Excelente" | "Muy bueno" | "Bueno"
   - tipo: "Sedán" | "SUV" | "Hatchback" | "Pickup" | "Utilitario"
   - financiacion: true/false  (si admite financiación)
   - destacado: true/false     (badge "Destacado")
   ========================================================================= */

const VEHICLES = [
  {
    id: "vw-golf-2019",
    marca: "Volkswagen",
    modelo: "Golf 1.4 TSI Highline",
    anio: 2019,
    km: 48000,
    precio: 21500,
    estado: "Excelente",
    tipo: "Hatchback",
    motor: "1.4 TSI Turbo",
    transmision: "Automática DSG",
    combustible: "Nafta",
    financiacion: true,
    destacado: true,
    documentacion: "Al día, con verificación policial y service oficial.",
    imagenes: [],
  },
  {
    id: "toyota-corolla-2021",
    marca: "Toyota",
    modelo: "Corolla 2.0 XEI CVT",
    anio: 2021,
    km: 32000,
    precio: 26900,
    estado: "Excelente",
    tipo: "Sedán",
    motor: "2.0 Dynamic Force",
    transmision: "Automática CVT",
    combustible: "Nafta",
    financiacion: true,
    destacado: true,
    documentacion: "Título y cédula al día. Único dueño.",
    imagenes: [],
  },
  {
    id: "ford-ranger-2020",
    marca: "Ford",
    modelo: "Ranger 3.2 Limited 4x4",
    anio: 2020,
    km: 75000,
    precio: 34500,
    estado: "Muy bueno",
    tipo: "Pickup",
    motor: "3.2 Turbodiésel",
    transmision: "Automática",
    combustible: "Diésel",
    financiacion: true,
    destacado: false,
    documentacion: "Service al día. Lista para transferir.",
    imagenes: [],
  },
  {
    id: "chevrolet-onix-2022",
    marca: "Chevrolet",
    modelo: "Onix 1.0 Turbo Premier",
    anio: 2022,
    km: 19000,
    precio: 18900,
    estado: "Excelente",
    tipo: "Hatchback",
    motor: "1.0 Turbo",
    transmision: "Automática",
    combustible: "Nafta",
    financiacion: true,
    destacado: false,
    documentacion: "Como nuevo. Garantía de fábrica vigente.",
    imagenes: [],
  },
  {
    id: "peugeot-208-2018",
    marca: "Peugeot",
    modelo: "208 1.6 Feline",
    anio: 2018,
    km: 62000,
    precio: 13500,
    estado: "Bueno",
    tipo: "Hatchback",
    motor: "1.6 16v",
    transmision: "Manual",
    combustible: "Nafta",
    financiacion: false,
    destacado: false,
    documentacion: "Al día. Listo para patentar.",
    imagenes: [],
  },
  {
    id: "vw-amarok-2019",
    marca: "Volkswagen",
    modelo: "Amarok 2.0 Highline 4x4",
    anio: 2019,
    km: 88000,
    precio: 31000,
    estado: "Muy bueno",
    tipo: "Pickup",
    motor: "2.0 Biturbo TDI",
    transmision: "Automática",
    combustible: "Diésel",
    financiacion: true,
    destacado: false,
    documentacion: "Service oficial. Verificada.",
    imagenes: [],
  },
  {
    id: "jeep-renegade-2021",
    marca: "Jeep",
    modelo: "Renegade 1.8 Sport",
    anio: 2021,
    km: 41000,
    precio: 23800,
    estado: "Excelente",
    tipo: "SUV",
    motor: "1.8 E.torQ",
    transmision: "Automática",
    combustible: "Nafta",
    financiacion: true,
    destacado: true,
    documentacion: "Único dueño. Documentación verificada.",
    imagenes: [],
  },
  {
    id: "renault-kangoo-2020",
    marca: "Renault",
    modelo: "Kangoo Express Confort",
    anio: 2020,
    km: 95000,
    precio: 12900,
    estado: "Bueno",
    tipo: "Utilitario",
    motor: "1.6 16v",
    transmision: "Manual",
    combustible: "Nafta",
    financiacion: false,
    destacado: false,
    documentacion: "Ideal trabajo. Al día.",
    imagenes: [],
  },
  {
    id: "fiat-cronos-2022",
    marca: "Fiat",
    modelo: "Cronos 1.3 Drive",
    anio: 2022,
    km: 27000,
    precio: 15500,
    estado: "Excelente",
    tipo: "Sedán",
    motor: "1.3 Firefly",
    transmision: "Manual",
    combustible: "Nafta",
    financiacion: true,
    destacado: false,
    documentacion: "Bajo kilometraje. Como nuevo.",
    imagenes: [],
  },
];
